### ISSUE TITLE
Statuses

### ISSUE THREAD

**Issue by johnhwyman** [rowlandan25/osTicket-Modules#12]
I installed this mod, but I only see the 3 items in Change Status,

Also, I cannot click the check box on the 
Ticket Status Module - Custom Actions

John

**Comment by rowlandan25** [comment]
Can you post a picture of where you only see the 3 items?

Also - the custom actions are ready to go yet which is why it is disabled.

**Comment by johnhwyman** [comment]
![status](https://cloud.githubusercontent.com/assets/9091979/5096662/18627820-6f42-11e4-8112-1e6307dec5ac.jpg)

**Comment by rowlandan25** [comment]
If you go to Admin Panel -> Manage -> Lists -> Ticket Statuses are there any additional ones there?

Open, Resolved and Closed are the default statuses in the system.  If you are upgrading from a previous build of the module pack, they will be migrated over.  If you are testing it on a fresh system you will need to add new statuses in the list I directed you to above.

**Comment by johnhwyman** [comment]
![status2](https://cloud.githubusercontent.com/assets/9091979/5096781/16077b24-6f43-11e4-861c-5f18870182a5.jpg)
There were 5 in the list, I added 2 more, byt still the Status chooser only shows 3

**Comment by johnhwyman** [comment]
this was a fresh install of 1.9.4, you can see it at wyman.org/Support
agent (admin) test
password test

**Comment by rowlandan25** [comment]
Something 1 and Something 2 need to have the color properties added before they will work (which is why the properties box is red).  Archived and deleted will not show in that list.
