### ISSUE TITLE
Unable to update settings - correct errors below and try again

### ISSUE THREAD

**Issue by raj2ras** [rowlandan25/osTicket-Modules#16]
On 1.9.4 stable. 

When O try to " Initialize Module Package Now" . It fails with  "Unable to update settings - correct errors below and try again" 

No errors are shown.

Thanks.

**Comment by rowlandan25** [comment]
Are you upgrading or is it a fresh install?

**Comment by rowlandan25** [comment]
Can you post the log files for osTicket and the web (apache) error log.

**Comment by raj2ras** [comment]
It is a fresh install on a fully functioning OST 1.9.4 . Followed instructions and uploaded/overwrote files.  All else is working fine after upload.

Below  are the OST error logs.

**From OST:**
DB Error #1050
[CREATE TABLE ost_mod_status_object(id INT(64) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), objectName VARCHAR(64), tag INT(16) NULL DEFAULT NULL)] Table 'ost_mod_status_object' already exists

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1050', '[CREATE TABLE o...')
 #1 (root)/include/staff/modules.inc.php(175): db_query('CREATE TABLE os...')
 #2 (root)/include/staff/modules.inc.php(31): initialize('status')
 #3 (root)/scp/settings.php(48): update_modules()
 #4 {main}

**Apache error logs are empty on my HostGator!**

**Comment by rowlandan25** [comment]
Okay, in your database drop all of the module tables.  Those include:

mod_list
mod_logs
mod_status_object
mod_status_object_properties

Keep in mind that you may have a prefix before those tables (such as ost_)

Make sure to download the newest module pack (Build 1009) and you can do a fresh install of it!

**Comment by raj2ras** [comment]
Here is info of my setup:

Server Information
osTicket Version    v1.9.4 (c18eac4)
Web Server Software Apache
MySQL Version   5.5.40
PHP Version 5.4.34
PHP Extensions
gdlib    Used for image manipulation and PDF printing
imap     Used for email fetching
xml  XML API
xml-dom  Used for HTML email processing
json     Improves performance creating and processing JSON
mbstring     Highly recommended for non western european language content
phar     Highly recommended for plugins and language packs
PHP Settings
cgi.fix_pathinfo     "1" is recommended if AJAX is not working
date.timezone    America/Chicago
Database Information and Usage
Schema  summit_osttest (localhost)
Schema Signature    b26f29a6bb5dbb3510b057632182d138
Space Used  29.15 MiB
Space for Attachments   24.31 MiB

**Comment by raj2ras** [comment]
Did that, dropped the tables and uploaded build 1009. Still getting errors! Can I paste the errors?

**Comment by rowlandan25** [comment]
Yea, please do that!

**Comment by raj2ras** [comment]
Thank you for your efforts. Here are some typical errors:

DB Error #1146
[SELECT moduleName, modulePath, icon FROM ost_mod_list ORDER BY moduleName ASC] Table 'summit_osttest.ost_mod_list' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')
 #1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')
 #2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()
 #3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')
 #4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')
 #5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')
 #6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')
 #7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')
 #8 {main}

 DB Error #1146
[SELECT moduleName, modulePath, icon FROM ost_mod_list ORDER BY moduleName ASC] Table 'summit_osttest.ost_mod_list' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')
 #1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')
 #2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()
 #3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')
 #4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')
 #5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')
 #6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')
 #7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')
 #8 {main}

DB Error #1050
[CREATE TABLE ost_mod_status_object(id INT(64) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), objectName VARCHAR(64), tag INT(16) NULL DEFAULT NULL)] Table 'ost_mod_status_object' already exists

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1050', '[CREATE TABLE o...')
 #1 (root)/include/staff/modules.inc.php(145): db_query('CREATE TABLE os...')
 #2 (root)/include/staff/modules.inc.php(26): initialize('status')
 #3 (root)/scp/settings.php(48): update_modules()
 #4 {main}

 DB Error #1064
[INSERT INTO ost_form_field (form_id, label, required, name, sort, edit_mask, created, updated) VALUES (, 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())' at line 1

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[INSERT INTO os...')
 #1 (root)/include/staff/modules.inc.php(353): db_query('INSERT INTO ost...')
 #2 (root)/include/staff/modules.inc.php(152): build1008()
 #3 (root)/include/staff/modules.inc.php(26): initialize('status')
 #4 (root)/scp/settings.php(48): update_modules()
 #5 {main}

 DB Error #1064
[INSERT INTO ost_mod_logs (logName, logDetail, logType) VALUES ('Query Failed', 'Failed to execute query: INSERT INTO ost_form_field (form_id, label, required, name, sort, edit_mask, created, updated) VALUES (, 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())', 3)] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Background Color', 1, 'bgcolor', 4, 15, NOW(), NOW())', 3)' at line 1

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[INSERT INTO os...')
 #1 (root)/include/staff/modules.inc.php(76): db_query('INSERT INTO ost...')
 #2 (root)/include/staff/modules.inc.php(353): logEntry('Query Failed', 'Failed to execu...', 3)
 #3 (root)/include/staff/modules.inc.php(152): build1008()
 #4 (root)/include/staff/modules.inc.php(26): initialize('status')
 #5 (root)/scp/settings.php(48): update_modules()
 #6 {main}

**Comment by rowlandan25** [comment]
I found the issue and it lies within the installer.  The fix is going to be pretty simple:

Log into your database and open up the configuration table (ost_config)
Find the 'key' of 'mod_status_sysbuild'
Change the 'value' from '1008' to '1009'
Find the 'key' of 'mod_status_version'
Change the 'value' to 'v1.9.4-1008 (alpha)'

**Comment by raj2ras** [comment]
Thanx. FYI, The keys were actually called "mod_pack_sysbuild" and "mod_pack_version", I just cloned them while leaving old keys, changed values and bingo - no errors.

That fixed the errors, now onto playing with this module :-)
