### ISSUE TITLE
status list colours in admin panel

### ISSUE THREAD

**Issue by nhybgtvfr** [rowlandan25/osTicket-Modules#17]
in the admin panel, 
modules - statuses.
in the status list box, the foreground and background colours are transposed. the border colour is ok.

when setting colour properties for the open status in the custom list, i set background to yellow, foreground to black, and border to orange.

the status module - manage statuses, shows the foreground as yellow, the background as black and the border as orange.

**Comment by rowlandan25** [comment]
I found the bugs and fixed that for the 1009 build.  Thanks for the input!
