### ISSUE TITLE
db errors

### ISSUE THREAD

**Issue by nhybgtvfr** [rowlandan25/osTicket-Modules#19]
i get similar, but different errors as raj2ras, so posting this separately in case it's a different bug.

completely new clean install of osticket 1.9.4, copy over mod files.  go to settings - modules
initialize the module
i then go to the ticket list, assign colours to the open status entry.
    - the colours and shape display fine in modules - statuses - status list

return to the module settings. 
i can see ticket status module, with upgrade to 1009, no other options, and ticket status module - custom actions, with enable module greyed out. 
i select upgrade to 1009. 
again i see ticket status module, with upgrade to 1009, no other options, and ticket status module - custom actions, now with a list of possible actions.
i select upgrade to 1009 again, now i can see enable module, and show column in queue.
the list of possible actions in the custom actions area has disappeared. 
i select  enable module and show column in queue and click on save changes. 
  when i check modules - statuses - status list, or the ticket queue in http://url/scp/
   the foreground and background colours are ok, there is no shape or border displayed. 

system : ubuntu 12.04.2 LTS,  php 5.5.15rc1, mysql 14.14 Distrib 5.5.32
no errors logged in apache, can't see anything useful in mysql logs. i turned on general logging, so i do have a record of all the mysql queries being made.

 i receive a few emails for different DB error 1146's, in order:

[SELECT moduleName, modulePath, icon FROM ost2_mod_list ORDER BY moduleName ASC]

Table 'osticket2.ost2_mod_list' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')<br />
#1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')<br />
#2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()<br />
#3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')<br />
#4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')<br />
#5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')<br />
#6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')<br />
#7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')<br />
#8 {main}

[SELECT id, statusName FROM ost2_mod_status WHERE active=1]

Table 'osticket2.ost2_mod_status' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT id, sta...')<br />
#1 (root)/include/staff/settings-modules.inc.php(158): db_query('SELECT id, stat...')<br />
#2 (root)/scp/settings.php(66): include_once('/var/www/vhosts...')<br />
#3 {main}

[SELECT id, statusName FROM ost2_mod_status WHERE active=1]

Table 'osticket2.ost2_mod_status' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT id, sta...')<br />
#1 (root)/include/staff/settings-modules.inc.php(158): db_query('SELECT id, stat...')<br />
#2 (root)/scp/settings.php(66): include_once('/var/www/vhosts...')<br />
#3 {main}

**Comment by rowlandan25** [comment]
I found the issue and it lies within the installer.  The fix is going to be pretty simple:

Log into your database and open up the configuration table (ost_config)
Find the 'key' of 'mod_status_sysbuild'
Change the 'value' from '1008' to '1009'
Find the 'key' of 'mod_status_version'
Change the 'value' to 'v1.9.4-1008 (alpha)'

**Comment by raj2ras** [comment]
Same here. More DB errors after above fix and still no "Custom Ticket Lists" yet.  Giving up for now, till bugs are resolved.
