### ISSUE TITLE
db errors and status shape

### ISSUE THREAD

**Issue by nhybgtvfr** [rowlandan25/osTicket-Modules#20]
just tried the hotfix version on a clean 1.9.4 install. 
seemed ok on initialize, received 2 emails for db error 1146 when saving changes having selected enable module and show column in queue.  -- this was done quite quickly after the initialize, so the emails could still be in relation to the initialization of the module.

the status shape and border still don't display in the preview in the status list section on modules - statuses in the admin system, or in the status column in the scp system
the shape and border does display in the object list in modules - statuses on the admin system.

entries in config table are ok:

**************************\* 101. row ***************************
       id: 101
namespace: core
      key: mod_status_version
    value: v1.9.4-1009 (alpha)
  updated: 2014-11-21 11:15:43
**************************\* 102. row ***************************
       id: 102
namespace: core
      key: mod_status_sysbuild
    value: 1009
  updated: 2014-11-21 11:15:43
102 rows in set (0.00 sec)

db errors were identical:
[SELECT moduleName, modulePath, icon FROM ost2_mod_list ORDER BY moduleName ASC]

Table 'osticket2.ost2_mod_list' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')<br />
#1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')<br />
#2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()<br />
#3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')<br />
#4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')<br />
#5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')<br />
#6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')<br />
#7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')<br />
#8 {main}

the table does exist:

| ost2_list                         |
| ost2_list_items                   |
| ost2_mod_list                     |
| ost2_mod_logs                     |
| ost2_mod_status_object            |
| ost2_mod_status_object_properties |
| ost2_note                         |
| ost2_organization                 |

**Comment by rowlandan25** [comment]
Did you mean to post without a description?

**Comment by nhybgtvfr** [comment]
nope, accidentally hit the enter key.

**Comment by nhybgtvfr** [comment]
re: the status shape. i assigned colours to the open status before enabling the module.
i've just applied some more colours to the resolved status and now the shapes and border are displayed ok.

**Comment by nhybgtvfr** [comment]
seems i got a bit ahead of myself there. 
the shape and colours are now ok in the admin panel.

the shape, foreground colour, and background colour are ok in the agent panel, the border colour is still displaying the default colour even though another colour has been assigned.

**Comment by rowlandan25** [comment]
Ok, I will look into this.  Could you just do me a favor and post a picture of that.  Thanks!

**Comment by nhybgtvfr** [comment]
![mod-admin](https://cloud.githubusercontent.com/assets/5228733/5142709/34c9f8b0-717e-11e4-82f8-10ff91edd80e.jpg)
![mod-scp](https://cloud.githubusercontent.com/assets/5228733/5142715/4a90deb6-717e-11e4-8080-61a86edba814.jpg)

**Comment by rowlandan25** [comment]
Turned out to be a stupid semi-colon.  This will be in the 1010 release.

**Comment by rowlandan25** [comment]
The database errors should be taken care of as of build 1010.  Please try it out and let me know.
