### ISSUE TITLE
DB Error #1146

### ISSUE THREAD

**Issue by johnhwyman** [rowlandan25/osTicket-Modules#21]
I did a clean install of 1.9.4 Open Admin, all is good
I copy the HotFix files over and login in as admin, I did not access module setup page or anything else. I will await input before I attempt to open Module Settings Page.
received the following errors in order:
1st

Table 'wyman932_osticket.ost_mod_list' doesn't exist<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')<br />
#1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')<br />
#2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()<br />
#3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')<br />
#4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')<br />
#5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')<br />
#6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')<br />
#7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')<br />
#8 {main}

2nd
[SELECT moduleName, modulePath, icon FROM ost_mod_list ORDER BY moduleName ASC]

Table 'wyman932_osticket.ost_mod_list' doesn't exist<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')<br />
#1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')<br />
#2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()<br />
#3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')<br />
#4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')<br />
#5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')<br />
#6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')<br />
#7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')<br />
#8 (root)/scp/admin.php(3): require('/home/wyman932/...')<br />
#9 {main}

3rd
[SELECT moduleName, modulePath, icon FROM ost_mod_list ORDER BY moduleName ASC]

Table 'wyman932_osticket.ost_mod_list' doesn't exist<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT moduleN...')<br />
#1 (root)/include/class.nav.php(281): db_query('SELECT moduleNa...')<br />
#2 (root)/include/class.nav.php(46): AdminNav->getSubMenus()<br />
#3 (root)/include/class.nav.php(192): StaffNav->__get('submenus')<br />
#4 (root)/include/class.nav.php(196): StaffNav->getSubMenu('settings')<br />
#5 (root)/include/class.nav.php(97): StaffNav->getSubNav('settings')<br />
#6 (root)/include/class.nav.php(78): StaffNav->setActiveSubMenu('settings.php?t=...', 'settings')<br />
#7 (root)/scp/settings.php(64): StaffNav->setTabActive('settings', 'settings.php?t=...')<br />
#8 {main}

**Comment by rowlandan25** [comment]
These database errors should be fixed in Build 1010.  Please try it out and let me know.
