### ISSUE TITLE
Language Pack es_ES.phar DB error 1064 / 1146

### ISSUE THREAD

**Issue by xtura** [rowlandan25/osTicket-Modules#22]
Tried a clean install in default english and all seems correct apart from 1146 DB error already reported.

In a clean install in Spanish (es_ES.phar) I cannot activate the module with error 1064

[SELECT id, propertyName, valueCurrent FROM ost_mod_status_object_properties WHERE objectId=]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT id, pro...')<br />
#1 (raíz)/include/staff/modules-shape.inc.php(52): db_query('SELECT id, prop...')<br />
#2 (raíz)/scp/module.php(138): include_once('/datos/www/zent...')<br />
#3 {main}

In another attempt to activate the module DB error 1050

[CREATE TABLE ost_mod_status_object(id INT(64) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id), objectName VARCHAR(64), tag INT(16) NULL DEFAULT NULL)]

Table 'ost_mod_status_object' already exists<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1050', '[CREATE TABLE o...')<br />
#1 (raíz)/include/staff/modules.inc.php(145): db_query('CREATE TABLE os...')<br />
#2 (raíz)/include/staff/modules.inc.php(26): initialize('status')<br />
#3 (raíz)/scp/settings.php(48): update_modules()<br />
#4 {main}

Best regards,

Xtura

**Comment by rowlandan25** [comment]
Please clear your database logs, update to build 1010 and try again.  I fixed the database errors that you are experiencing.  Please let me know if that does not fix the problem (and post your new logs).  Thanks!
