### ISSUE TITLE
ticket edit functionality brake

### ISSUE THREAD

**Issue by liebendkl** [rowlandan25/osTicket-Modules#6]
Hi, i have clear installation for testing status mod, 

All module features work grat! but i have notised that with these module we cant edit tickets

when edit ticket and fill information to custom fields, can`t save ticket with white blank page

**Comment by rowlandan25** [comment]
Is this when you are updating an existing field or adding new information?

**Comment by liebendkl** [comment]
/_<![CDATA[_/
 blockquote.c2 {border-left: 1px solid #cccccc; margin: 0pt 0pt 0pt 0.8ex; padding-left: 1ex}
 p.c1 {color: #666; font-size: small}
/_]]>_/

It is in both variants ((
 
Citējot Andrew Rowland notifications@github.com :

Is this when you are updating an existing field or adding new information?

##

**Comment by liebendkl** [comment]
Error when open ticket page : 

Warning: Cannot modify header information - headers already sent by (output started at /homepages/40/d371379376/htdocs/test_osticket/include/staff/header.inc.php:74) in /homepages/40/d371379376/htdocs/test_osticket/include/staff/header.inc.php on line 82

error when save changed ticket

blank page -
Fatal error: Call to undefined method DynamicFormEntry::setSource() in /homepages/40/d371379376/htdocs/test_osticket/scp/tickets.php on line 208

**Comment by liebendkl** [comment]
Today have installed new clear osticket 1.9 , but the issue still appears in v1006 of your mod

**Comment by rowlandan25** [comment]
When you look at your logs, are there any SQL errors present?

**Comment by liebendkl** [comment]
DB Error #1064
[SELECT ticket.ticket_id, tlock.lock_id, ticket.`number`, ticket.dept_id, ticket.staff_id, ticket.team_id , user.name , email.address as email, dept.dept_name , ticket.status, ticket.source, ticket.isoverdue, ticket.isanswered, ticket.created , status.statusName as statName, status.colorBG as bg, status.colorFG as fg, status.colorBD as bd , IF(ticket.duedate IS NULL, IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate , CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date , CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team , IF(staff.staff_id IS NULL, team.name, CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned , IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic , cdata.priority_id, cdata.subject, pri.priority_desc, pri.priority_color , cdata.priority as Custom1 ‘ FROM os_ticket ticket LEFT JOIN os_user user ON user.id = ticket.user_id LEFT JOIN os_user_email email ON user.id = email.user_id LEFT JOIN os_department dept ON ticket.dept_id=dept.dept_id LEFT JOIN os_mod_status_assignments msa ON msa.ticketId=ticket.ticket_id LEFT JOIN os_mod_status status ON msa.statusId=status.id LEFT JOIN os_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW() AND tlock.staff_id!=1) LEFT JOIN os_staff staff ON (ticket.staff_id=staff.staff_id) LEFT JOIN os_team team ON (ticket.team_id=team.team_id) LEFT JOIN os_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1) LEFT JOIN os_help_topic topic ON (ticket.topic_id=topic.topic_id) LEFT JOIN os_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid) LEFT JOIN os_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id) LEFT JOIN os_ticket_priority pri ON (pri.priority_id = cdata.priority_id) WHERE ( ( ticket.staff_id=1 AND ticket.status="open") OR ticket.dept_id IN (2) ) AND ticket.status='open' AND ticket.isanswered=0 AND ticket.staff_id=0 ORDER BY user.name DESC LIMIT 0, 25] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '‘ FROM os_ticket ticket LEFT JOIN os_user user ON user.id = ticket.user_id L' at line 1

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(169): osTicket->logDBError('DB Error #1064', '[SELECT ticket....')
 #1 (root)/include/staff/tickets.inc.php(262): db_query('SELECT ticket.t...')
 #2 (root)/scp/tickets.php(637): require_once('/homepages/40/d...')
 #3 {main}

**Comment by rowlandan25** [comment]
There error in your code is the apostraphy between the bracket (I added the bracket):
cdata.priority as Custom1 [‘] FROM os_ticket ticket 

I looked through the current github code, the release code and the code on my test machine and I cannot find this section of code:

 , cdata.priority as Custom1 ‘

Do you see this line in your code?  If you delete the single quote does the error stop?
Also, have you modified the code in any way other than copying my code over?
