### ISSUE TITLE
how to create shape properties

### ISSUE THREAD

**Issue by johnnybravo7** [rowlandan25/osTicket-Modules#7]
To set up a shape, go to Status Objects on the Modules sub menu. Click on Add New Object. Here, you are only asked for a name. Once you create the shape, you will be taken back to the list. If you click on edit (next to your new shape), you are able to add any CSS property you wish. Keep in mind, the properties are being assigned to a DIV.

**Comment by rowlandan25** [comment]
In Build 1008, a default shape is auto added for convenience.  Feel free to take a look at those properties or modify as needed.
